Remove unnecessary favicon url which demands staticfile exists.
chilli-axe/mpc-autofill pull request #229
Opened 2024-03-26 04:53 UTC by Investigamer

# Description

Fix crash caused by missing favicon.ico static file.

# Checklist

- [x] I have installed `pre-commit` and installed the hooks with `pre-commit install` before creating any commits.
- [x] I have updated any related tests for code I modified or added new tests where appropriate.
- [x] I have updated any relevant documentation or created new documentation where appropriate.

2024-03-26 05:22 UTC, ndepaola requested changes
* the frontend relies on the server having a `favicon.ico` file for the second step of the server connection workflow (using `ping.js`):
![image](https://github.com/chilli-axe/mpc-autofill/assets/3079166/532272c1-2067-45e3-8d0d-48870e51832c)

* if the system is deployed like you've configured it, where both the frontend and backend are hosted in the same domain, and any requests on `/2/` or `/admin/` are reverse proxied to django but other requests are reverse proxied to the frontend, then the *frontend's* `favicon.ico` will answer the ping request
* however, if the backend is deployed headlessly (without a frontend) and you try to connect to it through https://mpcautofill.github.io, i expect the ping step will fail because the backend has no `favicon.ico`
* so i reckon the correct change here is to revert the deletion of `favicon.ico` from #176

2024-03-26 23:20 UTC, Investigamer commented
Done 👍

2024-03-26 23:24 UTC, Investigamer reviewed
Done! Looks all set 👍

2024-03-27 23:22 UTC, ndepaola approved these changes

2024-03-27 23:22 UTC, merged